import { Share } from "@capacitor/share";
import { type NextPage } from "next";
import { apiBaseUrl } from "next-auth/client/_utils";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { BackgroundImage, Box } from "@mantine/core";
import { ButtonToggle } from "components/togglemoode";
import Navbar from "components/Navbar";


const Home: NextPage = () => {
  // const [sticker, setSticker] = useState([]);
  const share = async () => {
    await Share.share({
      title: "Sticker App",
      text: "Check out this app!",
      url: "https://stickerapp.vercel.app/",
      dialogTitle: "Share with friends",
    });
  };
  return (
    <>
      <Head>
        <title>Sticker App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#cffafe] to-[#164e63]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="font-outline-2 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Free
            <span className="text-blue-500">Sticker</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
         
              <div className="flex max-w-xs flex-col gap-4 border border-cyan-900 rounded-xl bg-white/50 hover:bg-slate-600 p-4 text-white">
                <h3 className="text-2xl font-bold">
                  Popular <span className="text-blue-500">Stickers</span>{" "}
                </h3>

                {}

                <div className="text-lg">
                  <div className="flex flex-row items-center justify-center  gap-4 space-x-2 overflow-x-auto scrollbar-hide">
                    <img
                      src="/Stickers/1.png"
                      alt="Sticker1"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/2.png"
                      alt="Sticker2"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/3.png"
                      alt="Sticker3"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/4.png"
                      alt="Sticker4"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/5.png"
                      alt="Sticker5"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/6.png"
                      alt="Sticker6"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/7.png"
                      alt="Sticker7"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/8.png"
                      alt="Sticker8"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/9.png"
                      alt="Sticker9"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/10.png"
                      alt="Sticker10"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/11.png"
                      alt="Sticker11"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/12.png"
                      alt="Sticker12"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/13.png"
                      alt="Sticker13"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/14.png"
                      alt="Sticker14"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/15.png"
                      alt="Sticker15"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/16.png"
                      alt="Sticker16"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/17.png"
                      alt="Sticker17"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/18.png"
                      alt="Sticker18"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/19.png"
                      alt="Sticker19"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/20.png"
                      alt="Sticker20"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/21.png"
                      alt="Sticker21"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/22.png"
                      alt="Sticker22"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/23.png"
                      alt="Sticker23"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/24.png"
                      alt="Sticker24"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/25.png"
                      alt="Sticker25"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/26.png"
                      alt="Sticker26"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/27.png"
                      alt="Sticker27"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/28.png"
                      alt="Sticker28"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/29.png"
                      alt="Sticker29"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/30.png"
                      alt="Sticker30"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/31.png"
                      alt="Sticker31"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/32.png"
                      alt="Sticker32"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/33.png"
                      alt="Sticker33"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/34.png"
                      alt="Sticker34"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/35.png"
                      alt="Sticker35"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/36.png"
                      alt="Sticker36"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/37.png"
                      alt="Sticker37"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/38.png"
                      alt="Sticker38"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/39.png"
                      alt="Sticker39"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/40.png"
                      alt="Sticker40"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/41.png"
                      alt="Sticker41"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/42.png"
                      alt="Sticker42"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/43.png"
                      alt="Sticker43"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/44.png"
                      alt="Sticker44"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/45.png"
                      alt="Sticker45"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/46.png"
                      alt="Sticker46"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/47.png"
                      alt="Sticker47"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/48.png"
                      alt="Sticker48"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/49.png"
                      alt="Sticker49"
                      className="h-20 w-20"
                    />
                    <img
                      src="/Stickers/50.png"
                      alt="Sticker50"
                      className="h-20 w-20"
                    />
                  </div>
                </div>
              </div>
         
             
              <div className="flex max-w-xs flex-col gap-4 rounded-xl p-4 bg-white/50 hover:bg-slate-600 text-white">
                <h3 className="text-2xl  font-bold">
                  Random <span className="text-blue-500"> Stickers</span>
                </h3>

                <div className="flex flex-row space-x-2 overflow-x-auto text-lg scrollbar-hide">
                  <img
                    src="/Stickers/51.png"
                    alt="Sticker51"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/52.png"
                    alt="Sticker52"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/53.png"
                    alt="Sticker53"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/54.png"
                    alt="Sticker54"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/55.png"
                    alt="Sticker55"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/56.png"
                    alt="Sticker56"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/57.png"
                    alt="Sticker57"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/58.png"
                    alt="Sticker58"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/59.png"
                    alt="Sticker59"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/60.png"
                    alt="Sticker60"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/61.png"
                    alt="Sticker61"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/62.png"
                    alt="Sticker62"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/63.png"
                    alt="Sticker63"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/64.png"
                    alt="Sticker64"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/65.png"
                    alt="Sticker65"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/66.png"
                    alt="Sticker66"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/67.png"
                    alt="Sticker67"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/68.png"
                    alt="Sticker68"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/69.png"
                    alt="Sticker69"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/70.png"
                    alt="Sticker70"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/71.png"
                    alt="Sticker71"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/72.png"
                    alt="Sticker72"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/73.png"
                    alt="Sticker73"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/74.png"
                    alt="Sticker74"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/75.png"
                    alt="Sticker75"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/76.png"
                    alt="Sticker76"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/77.png"
                    alt="Sticker77"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/78.png"
                    alt="Sticker78"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/79.png"
                    alt="Sticker79"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/80.png"
                    alt="Sticker80"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/81.png"
                    alt="Sticker81"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/82.png"
                    alt="Sticker82"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/83.png"
                    alt="Sticker83"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/84.png"
                    alt="Sticker84"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/85.png"
                    alt="Sticker85"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/86.png"
                    alt="Sticker86"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/87.png"
                    alt="Sticker87"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/88.png"
                    alt="Sticker88"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/89.png"
                    alt="Sticker89"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/90.png"
                    alt="Sticker90"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/91.png"
                    alt="Sticker91"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/92.png"
                    alt="Sticker92"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/93.png"
                    alt="Sticker93"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/94.png"
                    alt="Sticker94"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/95.png"
                    alt="Sticker95"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/96.png"
                    alt="Sticker96"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/97.png"
                    alt="Sticker97"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/98.png"
                    alt="Sticker98"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/99.png"
                    alt="Sticker99"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/100.png"
                    alt="Sticker100"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/101.png"
                    alt="Sticker101"
                    className="h-20 w-20"
                  />
                </div>
              </div>
          

            <div>
            <div className="flex max-w-xs flex-col gap-4 rounded-xl p-4 bg-white/50 hover:bg-slate-600 text-white">
                <h3 className="text-2xl  font-bold">
                  PePe <span className="text-blue-500"> Stickers</span>
                </h3>

                <div className="flex flex-row space-x-2 overflow-x-auto text-lg scrollbar-hide">
                  <img
                    src="/Stickers/51.png"
                    alt="Sticker51"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/52.png"
                    alt="Sticker52"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/53.png"
                    alt="Sticker53"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/54.png"
                    alt="Sticker54"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/55.png"
                    alt="Sticker55"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/56.png"
                    alt="Sticker56"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/57.png"
                    alt="Sticker57"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/58.png"
                    alt="Sticker58"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/59.png"
                    alt="Sticker59"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/60.png"
                    alt="Sticker60"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/61.png"
                    alt="Sticker61"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/62.png"
                    alt="Sticker62"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/63.png"
                    alt="Sticker63"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/64.png"
                    alt="Sticker64"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/65.png"
                    alt="Sticker65"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/66.png"
                    alt="Sticker66"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/67.png"
                    alt="Sticker67"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/68.png"
                    alt="Sticker68"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/69.png"
                    alt="Sticker69"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/70.png"
                    alt="Sticker70"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/71.png"
                    alt="Sticker71"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/72.png"
                    alt="Sticker72"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/73.png"
                    alt="Sticker73"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/74.png"
                    alt="Sticker74"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/75.png"
                    alt="Sticker75"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/76.png"
                    alt="Sticker76"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/77.png"
                    alt="Sticker77"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/78.png"
                    alt="Sticker78"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/79.png"
                    alt="Sticker79"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/80.png"
                    alt="Sticker80"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/81.png"
                    alt="Sticker81"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/82.png"
                    alt="Sticker82"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/83.png"
                    alt="Sticker83"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/84.png"
                    alt="Sticker84"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/85.png"
                    alt="Sticker85"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/86.png"
                    alt="Sticker86"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/87.png"
                    alt="Sticker87"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/88.png"
                    alt="Sticker88"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/89.png"
                    alt="Sticker89"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/90.png"
                    alt="Sticker90"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/91.png"
                    alt="Sticker91"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/92.png"
                    alt="Sticker92"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/93.png"
                    alt="Sticker93"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/94.png"
                    alt="Sticker94"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/95.png"
                    alt="Sticker95"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/96.png"
                    alt="Sticker96"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/97.png"
                    alt="Sticker97"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/98.png"
                    alt="Sticker98"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/99.png"
                    alt="Sticker99"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/100.png"
                    alt="Sticker100"
                    className="h-20 w-20"
                  />
                  <img
                    src="/Stickers/101.png"
                    alt="Sticker101"
                    className="h-20 w-20"
                  />
                </div>
              </div>
            </div>
          </div>
         
         
          <div>
           
           
           
            
          </div>
          <div>
            {/* save pictures  */}
            {/* <a className="border text-2xl text-white" onClick={() => save()}>
              Save{" "}
            </a> */}

          </div>
        <div className="">
          <Navbar/>
        </div>
          <div>
            <a className="border text-2xl text-white" onClick={() => share()}>
              Share{" "}
            </a>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
